spring.application.name=VLCApplication
# port
server.port=8080
# Nom de l'application Spring Boot
spring.application.name=PlayMusicVideoApplication
# URL de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/musicvideo_db?useSSL=false&serverTimezone=UTC
# Nom d'utilisateur pour la base de données
spring.datasource.username=root
# Mot de passe pour la base de données
spring.datasource.password=root
# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true
# Stratégie de génération du schéma de la base de données
spring.jpa.hibernate.ddl-auto=update
# Dialecte Hibernate pour MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Activer les logs de Spring Security (désactiver ou ajuster en production)
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG

# Stockage local
storage.mode=local
# Chemin local pour les fichiers (si stockage local)
# Chemin pour stocker les fichiers uploadés
music.upload.dir=./uploads


# Pour le stockage en ligne (ex. AWS S3)
storage.s3.bucket-name=your-bucket-name
storage.s3.access-key=your-access-key
storage.s3.secret-key=your-secret-key
